%  Reiteration of Marginal Distribution Functions Generated by t1

% Forming a 100*4 matrix of kernel distribution estimate values F_kx1\F_kx2\F_kx3\F_kx4 at 100 equally spaced points within the range of values for the residual data Xi
% Transposing 1-row-n-column matrices F_kx1\F_kx2\F_kx3\F_kx4 to n-row-1-column Fkx1\Fkx2\Fkx3\Fkx4
Fkx1 = F_kx1'; Fkx2 = F_kx2'; Fkx3 = F_kx3'; Fkx4 = F_kx4';
U = [F_kx1(:), F_kx2(:), F_kx3(:), F_kx4(:)];

% Combining the kernel distribution function values F_kx1q, F_kx2q, F_kx3q, and F_kx4q for various measurement points into a 4-dimensional random vector
T = [F_kx1q, F_kx2q, F_kx3q, F_kx4q];

% Computing Parameters for Gaussian and t Copula Functions

% 1. Computing Multidimensional Gaussian Copula

% Solving for the unknown parameter matrix (Pearson linear correlation coefficient matrix) for the multidimensional Gaussian Copula
Gaussian_Pearson = copulafit('Gaussian', U); % Gaussian_Pearson represents the unknown parameter matrix (Pearson linear correlation coefficients).
% Calculating AIC and BIC for the Gumbel distribution of kernel distribution estimate values F_kx1\F_kx2\F_kx3\F_kx4
[aic_k_gaussian4D, bic_k_gaussian4D] = gaussian_copula4D_aic_bic(U, Gaussian_Pearson);
% Calculating the cumulative distribution and probability density functions of the Gumbel distribution for kernel distribution estimate values F_kx1\F_kx2\F_kx3\F_kx4
F_k_Gaussian = copulacdf('Gaussian', U, Gaussian_Pearson); 
f_k_Gaussian = copulapdf('Gaussian', U, Gaussian_Pearson);

% Calculating AIC and BIC for the observed marginal distribution values F_kx1q, F_kx2q, F_kx3q, and F_kx4q
[aic_gaussian4D, bic_gaussian4D] = gaussian_copula4D_aic_bic(T, Gaussian_Pearson);
% Calculating the cumulative distribution and probability density functions of the Gumbel distribution for observed marginal distribution values F_kx1q, F_kx2q, F_kx3q, and F_kx4q
F_Gaussian = copulacdf('Gaussian', T, Gaussian_Pearson);
f_Gaussian = copulapdf('Gaussian', T, Gaussian_Pearson);
%%

% 2. Computing Multidimensional t Copula

% Solving for the unknown parameter matrix (Pearson linear correlation coefficient matrix) for the multidimensional t Copula
[t_Pearson, nuhat] = copulafit('t', U); % nuhat represents the degrees of freedom for the t Copula function. Note: Too small data or strong data dependencies can lead to inconclusive results. t_Pearson is the unknown parameter matrix.
% Calculating AIC and BIC for the Gumbel distribution of kernel distribution estimate values F_kx1\F_kx2\F_kx3\F_kx4
[aic_k_t4D, bic_k_t4D] = t_copula4D_aic_bic(U, t_Pearson, nuhat);
% Calculating the cumulative distribution and probability density functions of the Gumbel distribution for kernel distribution estimate values F_kx1\F_kx2\F_kx3\F_kx4
F_k_t = copulacdf('t', U, t_Pearson, nuhat); 
f_k_t = copulapdf('t', U, t_Pearson, nuhat);
%%
% Calculating AIC and BIC for the observed marginal distribution values F_kx1q, F_kx2q, F_kx3q, and F_kx4q
[aic_t4D, bic_t4D] = t_copula4D_aic_bic(T, t_Pearson, nuhat);
% Calculating the cumulative distribution and probability density functions of the Gumbel distribution for observed marginal distribution values F_kx1q, F_kx2q, F_kx3q, and F_kx4q
F_t = copulacdf('t', T, t_Pearson, nuhat); 
f_t = copulapdf





